GET http://localhost:8000/users

###

POST http://localhost:8000/users/register
Content-Type: application/json

{
    "pseudo": "Ryo",
    "password": "toto"
}

###

GET http://localhost:8000/users/87edce17-4c0f-4722-b54b-3b55030307ae

###

POST http://localhost:8000/users/login
Content-Type: application/json

{
    "pseudo": "toto",
    "password": "toto"
}

###

PUT  http://localhost:8000/users/a7697a78-90ed-4eeb-bcb1-9b4e7d8cc4d3/trials

###

PUT  http://localhost:8000/users/a7697a78-90ed-4eeb-bcb1-9b4e7d8cc4d3/trials